sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wengyehao123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: my-sky-take-out-heima
    access-key-id: LTAI5tCCW42WHa7gC6eZB6HF
    access-key-secret: 4QNUiW0zGwgEV567BNOVmOEEg8R3dT
  wechat:
    appid: wx189816a6dd169b25
    secret: e8823d58ca24132ff55b2f2c1687a278

